#!/bin/bash

# SSH Commands for Raspberry Pi - Copy and paste these commands

echo "🍓 Raspberry Pi Update Commands"
echo "=============================="
echo ""
echo "1. SSH to your Raspberry Pi:"
echo "   ssh matrix@192.168.0.117"
echo ""
echo "2. Navigate to project directory:"
echo "   cd wind-tunnel-rpi-v3"
echo ""
echo "3. Pull latest changes and update system:"
echo "   ./git-pull-update.sh"
echo ""
echo "4. Start the touchscreen demo:"
echo "   ./start-touchscreen-demo.sh"
echo ""
echo "5. Access the demo at:"
echo "   http://192.168.0.117:5000"
echo ""
echo "If you get permission errors, run first:"
echo "   chmod +x *.sh"
echo ""
echo "If git-pull-update.sh doesn't exist yet, run:"
echo "   git pull origin main"
echo "   chmod +x *.sh"
echo "   ./git-pull-update.sh"
echo ""
